---
- name: Deploy postgres
  hosts: appdbs
  gather_facts: false
  become: true
  tasks:

  - name: Install postgres
    package:
      name: postgresql-server
      state: present
  
  - name: Enable postgres at boot
    service:
      name: postgresql.service
      enabled: yes
      state: started
    register: postgres_service

  - name: Service state
    debug: msg="{{ postgres_service.status.ActiveState }}"
  
  - name: Initilize postgres
    block:
      - name: Initilize postgres
        command: postgresql-setup initdb

      - name: Check postgres config
        command: chkconfig postgresql on
    when:
      - postgres_service.status.ActiveState != 'active'
      - postgres_service.enable == 'true'