---
- name: Deploy postgres
  hosts: appdbs
  gather_facts: false
  become: true
  vars:
    postgres_service: postgresql.service

  tasks:
  - name: Install postgres
    package:
      name: postgresql-server
      state: present

  - name: Enable postgres at boot
    service:
      name: "{{ postgres_service }}"
      enabled: yes
    register: postgres_status
    ignore_errors: yes

  - name: Initilize postgres
    block:
      - name: Initilize postgres
        command: postgresql-setup initdb

      - name: Check postgres config
        command: chkconfig postgresql on
    when:
      - postgres_status.status.ActiveState != 'active'
  
  - name: Postgres service state
    debug: msg="{{ postgres_status.status.ActiveState }}"
  
  - name: Start postgres
    service:
      name: "{{ postgres_service }}"
      enabled: yes
      state: started
    register: postgres_status