---
- name: deploy tomcat
  hosts: apps
  gather_facts: false
  become: true
  vars:
    tomcat_dir: /usr/share/tomcat/webapps/ROOT

  tasks:
  - name: install tomcat
    package:
      name: tomcat
      state: present

  - name: create ansible tomcat directory
    file:
      path: "{{ tomcat_dir }}"
      state: directory

  - name: enable tomcat at boot
    service:
      name: tomcat
      enabled: yes
      state: started

  - name: copy static index.html to tomcat webapps/ansible/index.html
    template:
      src: index.html.apps
      dest: "{{ tomcat_dir }}/index.html"