---
- name: Cleanup Frontends
  hosts: frontends
  tags: cleanup_frontends
  gather_facts: false
  become: true

  tasks:
  - name: Stop HAProxy
    service:
      name: haproxy
      enabled: no
      state: stopped
    register: haproxy_service

  - name: Uninstall HAProxy package
    package:
      name: haproxy
      state: absent

  - name: Delete HAProxy directory
    file:
      state: absent
      path: /etc/haproxy/

- name: Cleanup Apps
  hosts: apps
  tags: cleanup_apps
  gather_facts: false
  become: true

  tasks:
  - name: Stop tomcat
    service:
      name: tomcat
      enabled: yes
      state: stopped

  - name: Remove tomcat
    package:
      name: tomcat
      state: absent

  - name: Delete tomcat directory
    file:
      state: absent
      path: /usr/share/tomcat/webapps/ROOT/

- name: Cleanup DB
  hosts: appdbs
  tags: cleanup_appdbs
  gather_facts: false
  become: true

  tasks:
  - name: Stop postgres
    service:
      name: postgresql.service
      enabled: no
      state: stopped
    register: postgres_service

  - name: Uninstall postgres
    package:
      name: postgresql-server
      state: absent