---
- name: deploy haproxy
  hosts: frontends
  gather_facts: false
  become: true

  tasks:
  - name: install HAProxy
    package:
      name: haproxy
      state: present

  - name: enable HAProxy
    service:
      name: haproxy
      enabled: yes
      state: started
    register: haproxy_service

  - name: configure haproxy
    template:
      src: ./haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
  
  handlers:
    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted